#!/usr/bin/env python3
"""Writes site/timezones.js: where each time zone is, from the system tz database.

The page picks its light or dark theme from where the sun is, and places the
listener at their time zone's principal city, so no location prompt is needed.
Rerun only to pick up a newer tz database:

    python3 tools/timezone_coordinates.py
"""

import collections
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
ZONEINFO = pathlib.Path("/usr/share/zoneinfo")


def degrees(text):
    # ISO 6709: ±DDMM[SS] or ±DDDMM[SS]
    whole = 3 if len(text) in (6, 8) else 2
    sign = -1 if text[0] == "-" else 1
    return sign * (int(text[1 : whole + 1]) + int(text[whole + 1 : whole + 3]) / 60)


places = {}
for line in (ZONEINFO / "zone.tab").read_text().splitlines():
    if line.startswith("#"):
        continue
    _, coordinates, zone = line.split("\t")[:3]
    latitude, longitude = re.fullmatch(r"([+-]\d+)([+-]\d+)", coordinates).groups()
    places[zone] = (round(degrees(latitude)), round(degrees(longitude)))

# Older names such as Asia/Calcutta, which some browsers still report.
for line in (ZONEINFO / "tzdata.zi").read_text().splitlines():
    if line.startswith("L "):
        _, target, alias = line.split()
        if target in places:
            places.setdefault(alias, places[target])

areas = collections.defaultdict(list)
for zone, (latitude, longitude) in sorted(places.items()):
    area, _, city = zone.partition("/")
    if city:
        areas[area].append(f"{city} {latitude} {longitude}")

table = ",\n  ".join(f"{area}: {json.dumps(','.join(cities))}" for area, cities in areas.items())
(ROOT / "site/timezones.js").write_text(
    "// Generated by tools/timezone_coordinates.py from the tz database: each time\n"
    "// zone's principal city as whole degrees of latitude and longitude, by area.\n"
    f"const timezoneCoordinates = {{\n  {table},\n}};\n"
)
